# Домашнее задание 0.

В этой домашке запрещается использовать циклы. Все задачи должны быть выполнены с помощью внутренних функций numpy и pandas.

In [2]:
import numpy as np
import pandas as pd
from numpy.testing import assert_equal, assert_array_equal
from pandas.testing import assert_frame_equal

# [OK] Ближайший элемент

Реализуйте функцию, принимающую на вход непустой тензор (может быть многомерным) $X$ и некоторое число $a$ и возвращающую ближайший к числу элемент тензора. Если ближайших несколько - выведите минимальный из ближайших. (Вернуть нужно само число, а не индекс числа!)

### Sample
#### Input:
```python
X = np.array([[ 1,  2, 13],
              [15,  6,  8],
              [ 7, 18,  9]])
a = 7.2
```
#### Output:
```python
7
```

# TASK

In [23]:
def nearest_value(X: np.ndarray, a: float) -> np.float64:
    vector = np.sort(np.ravel(X))-a
    nearest_negative = np.where(vector < 0, vector, -np.inf).max()
    nearest_positive = np.where(vector > 0, vector, np.inf).min()
    if abs(nearest_negative) <= nearest_positive:
        return nearest_negative + a 
    else:
        return nearest_positive + a

In [24]:
######################################################
assert_equal(
    nearest_value(np.array([ 1,  2, 13]), 10),
    13)
######################################################
assert_equal(
    nearest_value(np.array([ -1,  0]), -0.5),
    -1)
######################################################
assert_equal(
    nearest_value(np.array([[[ 1], [2],[3]],[[4],[5],[6]]]), 4.5),
    4)
######################################################
assert_equal(
    nearest_value(np.array([[ 1,  2, 13],
                            [15,  6,  8],
                            [ 7, 18,  9]]), 7.2),
    7)
######################################################
assert_equal(
    nearest_value(np.array([[ -1,  -2],
                            [-15,  -6]]), -100),
    -15)
######################################################
assert_equal(
    nearest_value(np.array([[ 2,  2],
                            [12,  12]]), 7),
    2)
######################################################
assert_equal(
    nearest_value(np.array([[ -2,  -2],
                            [-12,  -12]]), -7),
    -12)
######################################################

# [OK] Сортировка чисел

Дан одномерный массив целых чисел. Необходимо отсортировать в нем только числа, которые делятся на $2$. При этом начальный массив изменять нельзя.

### Sample
#### Input:
```python
A = np.array([43, 66, 34, 55, 78, 105, 2])
```
#### Output:
```python
array([ 43,   2,  34,  55,  66, 105,  78])
```


# TASK

In [42]:
import numpy as np

def sort_evens(A: np.ndarray) -> np.ndarray:
    a = np.copy(A)
    ind = np.where(a%2==0)
    a[ind] = np.sort(a[ind])
    return a

In [41]:
######################################################
assert_array_equal(sort_evens(np.array([])), np.array([]))
######################################################
assert_array_equal(sort_evens(np.array([2, 0])), np.array([0, 2]))
######################################################
assert_array_equal(sort_evens(np.array([9, 3, 1, 5, 7])), np.array([9, 3, 1, 5, 7]))
######################################################
assert_array_equal(sort_evens(np.array([8, 12, 4, 10, 6, 2])), np.array([2, 4, 6, 8, 10, 12]))
######################################################

# [OK] Страшные маски

Даны трехмерный тензор размерности $X(n, k, k)$, состоящий из $0$ или $1$, или $n$ картинок $k \times k$. Нужно применить к нему указанную маску размерности $(k, k)$: В случае, если биты в маске и картинке совпадают, то результирующий бит должен быть равен $0$, иначе $1$.

### Sample
#### Input:
```python
X = np.array([
              [[ 1, 0, 1],
               [ 1, 1, 1],
               [ 0, 0, 1]],
             
              [[ 1, 1, 1],
               [ 1, 1, 1],
               [ 1, 1, 1]]
            ])
mask = np.array([[1, 1, 0],
                 [1, 1, 0],
                 [1, 1, 0]])
```
#### Output:
```python
array([[[0, 1, 1],
        [0, 0, 1],
        [1, 1, 1]],

       [[0, 0, 1],
        [0, 0, 1],
        [0, 0, 1]]])
```


# TASK

In [46]:
import numpy as np

def tensor_mask(X: np.ndarray, mask: np.ndarray) -> np.ndarray:
    return X ^ mask

In [47]:
######################################################
X = np.zeros(9, dtype=int).reshape((1,3,3))
mask = np.zeros(9, dtype=int).reshape((3,3))
assert_array_equal(tensor_mask(X, mask), np.zeros(9, dtype=int).reshape((1,3,3)))
######################################################
X = np.zeros(9*3, dtype=int).reshape((3,3,3))
mask = np.ones(9, dtype=int).reshape((3,3))
assert_array_equal(tensor_mask(X, mask), np.ones(9*3, dtype=int).reshape((3,3,3)))
######################################################
X = np.array([[[ 1, 0, 1],
               [ 1, 1, 1],
               [ 0, 0, 1]]])
mask = np.array([[1, 1, 0],
                 [1, 1, 0],
                 [1, 1, 0]])
assert_array_equal(tensor_mask(X, mask), 
                   np.array([[[0, 1, 1],
                             [0, 0, 1],
                             [1, 1, 1]]]))
######################################################

# [OK] Сумма цифр в массиве

На вход подается `np.ndarray` c натуральными числами. Надо получить массив сумм цифр в этих числах.

### Sample
#### Input:
```python
a = np.array([1241, 354, 121])
```
#### Output:
```python
array([ 8, 12, 4])
```


# TASK

In [79]:
import numpy as np

def num_sum(a: np.ndarray) -> np.ndarray:
    c = a//10 ** np.arange(len(str(np.max(a))))[:, None] % 10
    return np.sum(c, axis=0)

In [80]:
######################################################
assert_array_equal(num_sum(np.array([82])), np.array([10]))
######################################################
assert_array_equal(num_sum(np.array([1241, 354, 121])), np.array([ 8, 12, 4]))
######################################################
assert_array_equal(num_sum(np.array([1, 22, 333, 4444, 55555])), np.array([1, 4, 9, 16, 25]))
######################################################                  

# [OK] Чистка NaN-ов

Одна из важных проблем данных - пустые значения. В *numpy* и *pandas* они обычно объявляются специальным типом ```np.nan```. В реальных задачах нам часто нужно что-то сделать с этими значениями. Например заменить на 0, среднее или медиану.

Реализуйте функцию, которая во входной вещественной матрице ```X``` находит все значения ```nan``` и заменяет их на **медиану** остальных элементов столбца. Если все элементы столбца матрицы ```nan```, то заполняем столбец нулями.

### Sample
#### Input:
```python
X = np.array([[np.nan,      4,  np.nan],
              [np.nan, np.nan,       8],
              [np.nan,      5,  np.nan]])
```
#### Output:
```python
array([[0. , 4. , 8. ],
       [0. , 4.5, 8. ],
       [0. , 5. , 8. ]])
```


# TASK

In [25]:
from pandas.io.parsers.base_parser import isna
import numpy as np

def replace_nans(X:np.ndarray) -> np.ndarray:    
    return np.where(np.isnan(X), np.ma.array(X, mask=np.isnan(X)).mean(axis=0), X)

In [27]:
from numpy.testing import assert_array_equal, assert_array_almost_equal
######################################################
assert_array_equal(replace_nans(
    np.array([[np.nan], [np.nan],  [np.nan]])),
    np.array([[0. ],[ 0. ],[ 0. ]])
)
######################################################
assert_array_equal(replace_nans(
    np.array([[0, 42,  42]])),
    np.array([[0, 42 , 42]])
)
######################################################
assert_array_equal(replace_nans(
    np.array([[np.nan], [1], [np.nan]])),
    np.array([[1.] ,[ 1.] ,[ 1. ]])
)
######################################################
assert_array_equal(replace_nans(
    np.array([[4], [1],  [np.nan]])),
    np.array([[4 ], [1] ,[ 2.5]])
)
######################################################
assert_array_equal(replace_nans(
    np.array([[np.nan, np.nan,  np.nan],
              [     4, np.nan,       5],
              [np.nan,      8,  np.nan]]).T),
    np.array([[0. , 0. , 0. ],
              [4. , 4.5, 5. ],
              [8. , 8. , 8. ]]).T
)
######################################################

# [OK] Бухгалтерия зоопарка

Вам на вход подается словарь, где ключ - это тип животного, а значение - словарь с признаками этого животного, где ключ - тип признака, а значение - значение признака (Типичный json проще говоря). Наименования признаков животного - всегда строки. Значения признаков - любой из типов pandas.

Вам следует создать табличку, где по строчкам будут идти животные, а по колонкам - их признаки, которая удовлетворяет следующим условиям:

* Тип животного нужно выделить в отдельную колонку `Type`
* Строки отсортированы по типу животного в алфавитном порядке
* Колонки отсортированы в алфавитном порядке, кроме колонки `Type` - она первая
* Индексы строк - ряд натуральных чисел начиная с 0 без пропусков

Имейте в виду, что признаки у двух животных могут не совпадать, значит незаполненные данные нужно заполнить `Nan` значением.

Верните на выходе табличку(`DataFrame`), в которой отсутствуют Nan значения. При этом могут отсутствовать некоторые признаки, но животные должны присутствовать **все**. Изначальные типы значений из словаря: `int64`, `float64`, `bool` и.т.д. должны сохраниться и в конечной табличке, а не превратиться в `object`-ы. (От удаляемых признаков этого, очевидно, не требуется).

### Sample 1
#### Input:
```python
ZOO = {
        'cat':{'color':'black', 'tail_len': 50, 'injured': False}, 
        'dog':{'age': 6, 'tail_len': 30.5, 'injured': True}
      }
```
#### Output:

|  | Type | injured |tail_len |
|--|----|--------|-------|
|0 | cat |  False | 50.0 |
|1 | dog |  True  | 30.5  |


# TASK

In [34]:
import numpy as np
import pandas as pd

def ZOOtable(zoo: dict) -> pd.DataFrame:
    df = pd.DataFrame.from_dict(zoo, orient='index').reset_index()
    df.rename(columns = {'index':'Type'}, inplace=True)
    df.sort_index(axis=1, inplace=True)
    df.sort_values("Type", inplace=True)
    df.dropna(axis=1,how='any', inplace=True)
    return df

In [35]:
######################################################
ZOO = {
        'cat': {'color':'black', 'tail_len': 50.0, 'injured': False}, 
        'dog': {'age': 6, 'tail_len': 30.5, 'injured': True}
      }
answer = pd.DataFrame(
    {
     'Type':['cat', 'dog'], 
     'injured':[False, True], 
     'tail_len':[50.0, 30.5]
    }
)
df = ZOOtable(ZOO)

assert_frame_equal(
    df.reset_index(drop=True),
    answer
)
######################################################
ZOO = {
        'cat': {'color':'black'}, 
        'dog': {'age': 6}
      }
answer = pd.DataFrame(
    {
     'Type':['cat', 'dog']
    }
)

df = ZOOtable(ZOO)

assert_frame_equal(
    df.reset_index(drop=True),
    answer
)
######################################################

# [OK] Простые преобразования

На вход подается `DataFrame` из 3-х колонок дата рождения и смерти человека на **русском** языке в формате представленом ниже:

|  | Имя             | Дата рождения  | Дата смерти      
|--|-----------------|----------------|------------------
|0 |Никола Тесла     |10 июля 1856 г. |7 января 1943 г.  
|1 |Альберт Эйнштейн |14 марта 1879 г.|18 апреля 1955 г.  

Необходимо вернуть исходную таблицу с добавленным в конце столбцом полных лет жизни.


|  | Имя             | Дата рождения  | Дата смерти     | Полных лет
|--|-----------------|----------------|-----------------|-----------
|0 |Никола Тесла     |10 июля 1856 г. |7 января 1943 г. | 86        
|1 |Альберт Эйнштейн |14 марта 1879 г.|18 апреля 1955 г.| 76        

Формат даты единый, исключений нет, пробелы мужду элементами дат присутствуют, исключений (`Nan`) нету.

P.S. Для обработки высокосных годов используйте модуль `dateutil.relativedelta`.

# TASK

In [41]:
import numpy as np
import pandas as pd
import dateutil.relativedelta as relativedelta
import datetime

rus_months = {
    'января': 1,
    'февраля' : 2,
    'марта' : 3,
    'апреля' : 4,
    'мая' : 5,
    'июня' : 6,
    'июля' : 7,
    'августа' : 8,
    'сентября' : 9,
    'октября' : 10,
    'ноября' : 11,
    'декабря' : 12
}

def parse_date(s_date: str) -> datetime:
    date = s_date.split(' ')
    return datetime.date(int(date[2]), rus_months[date[1]], int(date[0]))

def count_years(df):
    return relativedelta.relativedelta(parse_date(df['Дата смерти']), parse_date(df['Дата рождения'])).years

def rus_feature(df: pd.DataFrame) -> pd.DataFrame:
    df['Полных лет'] = df.apply(lambda data: count_years(data), axis=1)
    return df

In [42]:
######################################################
names = pd.DataFrame({'Имя':['Никола Тесла', 'Альберт Эйнштейн'], 
                   'Дата рождения':['10 июля 1856 г.','14 марта 1879 г.'],
                   'Дата смерти':  ['7 января 1943 г.', '18 апреля 1955 г.']})
answer = pd.DataFrame({'Имя':['Никола Тесла', 'Альберт Эйнштейн'], 
                       'Дата рождения':['10 июля 1856 г.','14 марта 1879 г.'],
                       'Дата смерти':  ['7 января 1943 г.', '18 апреля 1955 г.'],
                       'Полных лет':[86, 76]})
assert_frame_equal(
    rus_feature(names),
    answer
)
######################################################
names = pd.DataFrame({'Имя':['Никола Тесла'], 
                   'Дата рождения':['10 июля 1856 г.'],
                   'Дата смерти':  ['7 января 1857 г.']})
answer = pd.DataFrame({'Имя':['Никола Тесла'], 
                       'Дата рождения':['10 июля 1856 г.'],
                       'Дата смерти':  ['7 января 1857 г.'],
                       'Полных лет':[0]})
assert_frame_equal(
    rus_feature(names),
    answer
)
######################################################
names = pd.DataFrame({'Имя':['Никола Тесла'], 
                   'Дата рождения':['1 января 2000 г.'],
                   'Дата смерти':  ['31 декабря 2000 г.']})
answer = pd.DataFrame({'Имя':['Никола Тесла'], 
                       'Дата рождения':['1 января 2000 г.'],
                       'Дата смерти':  ['31 декабря 2000 г.'],
                       'Полных лет':[0]})
assert_frame_equal(
    rus_feature(names),
    answer
)

# Характеристики

В этой задаче на вход подаются всем известные данные о погибших/выживших пассажирах на титанике. (Файл `titanik_train.csv` в [папке data](https://github.com/samstikhin/ml2021/tree/master/01-Analysis/data)). 

Верните среднее, медиану, максимальное и минимальное значение возраста **погибших** мужчин. Именно в данном порядке.

### Sample 1
#### Input:
```python
df = pd.read_csv('titanic_train.csv', index_col='PassengerId')
```
#### Output:
```python
return 42,42,42,42
```

# TASK

In [45]:
def men_stat(df: pd.DataFrame) -> (float, float, float, float):
    df = df[(df['Survived']==0) & (df['Sex']=='male')]
    ages = df['Age']
    return (ages.mean(), ages.median(), ages.max(), ages.min())

In [49]:
df = pd.read_csv('titanic_train.csv', index_col='PassengerId')
men_stat(df)

(31.618055555555557, 29.0, 74.0, 1.0)

# Сводная таблица

В этой задаче на вход подаются всем известные данные о погибших/выживших пассажирах на титанике. (Файл `titanik_train.csv` в [папке data](https://github.com/samstikhin/ml2021/tree/master/01-Analysis/data)). 

Сделать сводную таблицу по **медианному возрасту** для пола и класса. Для примера посмотрите сводную таблицу по сумме выживших, для пола и класса. 

| Sex        | Pclass  | Survived |
|------------|---------|----------|
| **female** | **1**   |      91  |
|            | **2**   |      70  |
|            | **3**   |      72  |
| **male**   | **1**   |      45  |
|            | **2**   |      17  |
|            | **3**   |      47  |

Обратите внимание, что первые 2 столбца - это не колонки, а `MultiIndex`.

### Sample 1
#### Input:
```python
df = pd.read_csv('titanic_train.csv', index_col='PassengerId')
```

# TASK

In [46]:
def age_stat(df: pd.DataFrame) -> pd.DataFrame:
    return df.groupby(by=['Sex', 'Pclass']).median()[['Age']]

In [48]:
df = pd.read_csv('titanic_train.csv', index_col='PassengerId')
age_stat(df)

Age
Sex    Pclass      
female 1       35.0
       2       28.0
       3       21.5
male   1       40.0
       2       30.0
       3       25.0

# Популярные девушки

В этой задаче на вход подаются всем известные данные о погибших/выживших пассажирах на титанике. (Файл `titanik_train.csv` в [папке data](https://github.com/samstikhin/ml2021/tree/master/01-Analysis/data)). 

Выведите список имен незамужних женщин(`Miss`) отсортированный по популярности. 

* В полном имени девушек **имя** - это **первое слово без скобок** после `Miss`.
* Остальные строки не рассматриваем.
* Девушки с одинаковой популярностью сортируются по имени в алфавитном порядке.

**Слово/имя** - подстрока без пробелов.
**Популярность** - количество таких имен в таблице.

### Sample 1
#### Input:
```python
data = pd.read_csv('titanic_train.csv', index_col='PassengerId')
```
#### Output:
Вот начало данного списка. Заметьте, **названия колонок должны совпадать** 

|  | Name | Popularity |
|--|----|--------|
|0 |Anna |9|
|1 |Mary |9
|2 |Margaret|6
|3 |Elizabeth|5
|4 |Alice |4
|5 |Bertha |4
|6 |Ellen |4
|7 |Helen |4


# TASK

In [58]:
import re

def get_name(full_name):
    return re.search(r'Miss\. (\w*)', full_name).group(1)

def fename_stat(df: pd.DataFrame) -> pd.DataFrame:
    df = df[df['Name'].str.contains('Miss')]
    df['Name'] = df['Name'].apply(get_name)

    df = df.reset_index()[['Name']]
    df['Popularity'] = df['Name'].map(df['Name'].value_counts())

    df.drop_duplicates(subset='Name', keep="last", inplace=True)
    df.sort_values(['Popularity', 'Name'], ascending=[False, True], inplace=True)

    return df

In [59]:
df = pd.read_csv('titanic_train.csv', index_col='PassengerId')
fename_stat(df)

C:\Users\Никита\AppData\Local\Temp\ipykernel_12308\2839806570.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Name'] = df['Name'].apply(get_name)


Name  Popularity
167       Anna           9
175       Mary           9
180   Margaret           6
135  Elizabeth           5
154      Alice           4
..         ...         ...
53     Thamine           1
5      Torborg           1
127      Velin           1
165   Virginia           1
171     Wendla           1

[121 rows x 2 columns]